/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * ThinkEasy
 * Test Task BE
 * OpenAPI spec version: 1.0
 */
import type {
  Auth,
  CreatePostInput,
  LoginInput,
  PostResponce,
  PostResponse,
  RefreshResponceModel,
  RefreshTokenInput,
  SignupInput,
} from "./models";
import { apiClient } from "./apiClient";

export const getThinkEasy = () => {
  /**
   * @summary Signup a new user
   */
  const authControllerSignup = (signupInput: SignupInput) => {
    return apiClient<Auth>({
      url: `/auth/signup`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signupInput,
    });
  };

  /**
   * @summary Login an existing user
   */
  const authControllerLogin = (loginInput: LoginInput) => {
    return apiClient<Auth>({
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginInput,
    });
  };

  /**
   * @summary Refresh access token using a refresh token
   */
  const authControllerRefreshToken = (refreshTokenInput: RefreshTokenInput) => {
    return apiClient<RefreshResponceModel>({
      url: `/auth/refresh-token`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: refreshTokenInput,
    });
  };

  /**
   * @summary Create a new post
   */
  const postsControllerCreate = (createPostInput: CreatePostInput) => {
    return apiClient<PostResponce>({
      url: `/posts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPostInput,
    });
  };

  /**
   * @summary Get all posts
   */
  const postsControllerGetAllPosts = () => {
    return apiClient<PostResponse[]>({ url: `/posts`, method: "GET" });
  };

  /**
   * @summary Get all posts of a user
   */
  const postsControllerUserPosts = (userId: string) => {
    return apiClient<PostResponse[]>({
      url: `/posts/user/${userId}`,
      method: "GET",
    });
  };

  /**
   * @summary Get a post by its ID
   */
  const postsControllerPost = (postId: string) => {
    return apiClient<PostResponse>({ url: `/posts/${postId}`, method: "GET" });
  };

  return {
    authControllerSignup,
    authControllerLogin,
    authControllerRefreshToken,
    postsControllerCreate,
    postsControllerGetAllPosts,
    postsControllerUserPosts,
    postsControllerPost,
  };
};
export type AuthControllerSignupResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getThinkEasy>["authControllerSignup"]>>
>;
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getThinkEasy>["authControllerLogin"]>>
>;
export type AuthControllerRefreshTokenResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getThinkEasy>["authControllerRefreshToken"]>
  >
>;
export type PostsControllerCreateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getThinkEasy>["postsControllerCreate"]>>
>;
export type PostsControllerGetAllPostsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getThinkEasy>["postsControllerGetAllPosts"]>
  >
>;
export type PostsControllerUserPostsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getThinkEasy>["postsControllerUserPosts"]>
  >
>;
export type PostsControllerPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getThinkEasy>["postsControllerPost"]>>
>;
